/** Error classes returned by Pi operations, registrations, tools, and runtime shutdown. */
export {
  /** Event, command, shortcut, flag, tool, and renderer registration types. */
  type PiCommandDefinition,
  type PiCommandRegistry,
  /** Renderer types supported by Pi extensions. */
  type PiEntryRenderer,
  type PiEventHandler,
  type PiEventMap,
  type PiEventName,
  type PiEventOptions,
  type PiEventRegistry,
  type PiEventResultMap,
  /** Plugin definition and installation helpers. */
  PiExtension,
  type PiExtensionError,
  type PiFailurePolicy,
  type PiFlagDefinition,
  type PiFlagRegistry,
  type PiMessageRenderer,
  /** Plugin definition types accepted by the installation API. */
  type PiPlugin,
  type PiPluginDefinition,
  type PiRegistrationContext,
  PiRegistrationError,
  type PiRendererRegistry,
  PiRuntimeDisposedError,
  type PiShortcutDefinition,
  type PiShortcutRegistry,
  type PiToolRegistry,
} from './extension.ts'
export {
  /** Types for Effect-based tools and their results. */
  type EffectToolDefinition,
  /** Effect service tags for Pi operations and invocation context. */
  Pi,
  PiCommandContext,
  /** Context, session, UI, and service operation types. */
  type PiCommandContextValue,
  type PiCompactOptions,
  type PiContent,
  PiContext,
  type PiContextUsage,
  type PiCustomFactory,
  type PiCustomMessage,
  PiFlags,
  type PiInvocationServices,
  PiMessages,
  type PiMode,
  PiOperations,
  PiOperationsError,
  PiProcess,
  type PiSendMessageOptions,
  type PiSendUserMessageOptions,
  type PiServices,
  PiSession,
  type PiSessionChangeOptions,
  type PiSessionChangeResult,
  PiSessionContext,
  type PiSessionContextValue,
  type PiSessionReplacement,
  type PiStableServices,
  PiToolContext,
  type PiToolContextValue,
  PiToolError,
  type PiToolExecutionMode,
  type PiToolResult,
  PiTools,
  type PiToolUpdate,
  PiUi,
  type PiUiDialogOptions,
  type PiUiService,
  PiUiUnavailableError,
  type PiWidgetOptions,
  type PiWorkingIndicatorOptions,
} from './pi.ts'
